/**
 * Build-time content fetch: Sanity -> static TypeScript modules.
 * Run from project root: node scripts/fetch-content.mjs
 *
 * Generates src/data/settings.ts and src/data/projects.ts (gitignored).
 * No auth needed — reads from the public CDN.
 */
import { createClient } from '@sanity/client';
import { writeFileSync, mkdirSync } from 'fs';

const client = createClient({
  projectId: 'wqqh5015',
  dataset: 'production',
  useCdn: true,
  apiVersion: '2025-03-01',
});

const SETTINGS_QUERY = `*[_type == "siteSettings"][0]{
  name, descriptor, githubUrl, repoUrl,
  tagline, taglineAttribution, taglineUrl,
  intro, projectsTeaser, aboutTeaser,
  aboutImprov, aboutMovies, aboutTtrpgs, aboutCode,
  "socialLinks": coalesce(socialLinks[]{ label, href }, [])
}`;

const PROJECTS_QUERY = `*[_type == "project"] | order(displayOrder asc){
  name, "slug": slug.current, category,
  description, tech, link, repo, displayOrder, status
}`;

const HEADER = '// Auto-generated by scripts/fetch-content.mjs — do not edit\n';

const [settings, projects] = await Promise.all([
  client.fetch(SETTINGS_QUERY),
  client.fetch(PROJECTS_QUERY),
]);

if (!settings) {
  console.error('No siteSettings document found in Sanity.');
  process.exit(1);
}

mkdirSync('src/data', { recursive: true });

writeFileSync(
  'src/data/settings.ts',
  `${HEADER}import type { SiteSettings } from '@/lib/queries';\n\nexport const settings: SiteSettings = ${JSON.stringify(settings, null, 2)};\n`,
);

writeFileSync(
  'src/data/projects.ts',
  `${HEADER}import type { Project } from '@/lib/queries';\n\nexport const projects: Project[] = ${JSON.stringify(projects, null, 2)};\n`,
);

console.log('Content fetched from Sanity and written to src/data/.');
