/**
 * Sync GIF/WebP files from source folders into public/gifs/
 * and regenerate content/gifs.yaml.
 *
 * Source: ~/OneDrive/Pictures/{Dropout, Game Grumps, YouTube, Movies & TV}
 * Target: public/gifs/  (all files flat in one directory)
 *
 * Tags are derived from the folder hierarchy (show/series name).
 * Featured status is determined by presence in public/gifs/featured/.
 *
 * Usage: node scripts/sync-gifs.mjs
 */

import { copyFileSync, mkdirSync, writeFileSync, existsSync, readdirSync, statSync } from 'fs';
import { execFileSync } from 'child_process';
import { join, extname, basename, relative, sep } from 'path';
import { homedir } from 'os';

const PICTURES = join(homedir(), 'OneDrive', 'Pictures');
const YAML_PATH = 'content/gifs.yaml';

const SOURCES = [
  'Dropout',
  'Game Grumps',
  'YouTube',
  'Movies & TV',
];

const EXTS = new Set(['.gif', '.webp']);
const TARGET = 'public/gifs';
const FEATURED_DIR = join(TARGET, 'featured');
/** Episode-like folder names to skip when deriving tags. */
const EP_PATTERN = /^(ep\s*\d+|\d+(\.\d+)?)$/i;

/** Rename folder names to preferred display names. */
const TAG_RENAMES = new Map([
  ['Gamechanger', 'Game Changer'],
]);

function slugify(name) {
  return name
    .replace(extname(name), '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

/** Recursively collect all GIF/WebP files from a directory. */
function collectFiles(dir) {
  const results = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      results.push(...collectFiles(full));
    } else if (EXTS.has(extname(entry).toLowerCase())) {
      results.push(full);
    }
  }
  return results;
}

/**
 * Derive tags from the path between the source folder and the file.
 * Always includes the source folder (e.g. "Dropout") plus any
 * non-episode subfolder names (e.g. "Gamechanger").
 */
function deriveTags(srcPath, srcDir, sourceFolder) {
  const rel = relative(srcDir, srcPath);
  const parts = rel.split(sep).slice(0, -1); // drop filename
  const subTags = parts.filter((p) => !EP_PATTERN.test(p));
  const raw = [sourceFolder, ...subTags];
  return raw.map((t) => TAG_RENAMES.get(t) || t);
}

// Build set of featured filenames from the featured subfolder
const featuredFiles = new Set();
if (existsSync(FEATURED_DIR)) {
  for (const f of readdirSync(FEATURED_DIR)) {
    if (EXTS.has(extname(f).toLowerCase())) {
      featuredFiles.add(f);
    }
  }
  console.log(`${featuredFiles.size} files in featured/`);
}

mkdirSync(TARGET, { recursive: true });

const entries = [];
const seenSlugs = new Set();
const seenFiles = new Map(); // filename -> srcPath, detect collisions

for (const folder of SOURCES) {
  const srcDir = join(PICTURES, folder);
  if (!existsSync(srcDir)) {
    console.warn(`Skipping missing folder: ${srcDir}`);
    continue;
  }

  const files = collectFiles(srcDir);

  for (const srcPath of files) {
    const file = basename(srcPath);

    // Warn on filename collision from different sources
    if (seenFiles.has(file) && seenFiles.get(file) !== srcPath) {
      console.warn(`  Collision: "${file}" exists in multiple folders, last one wins`);
    }
    seenFiles.set(file, srcPath);
    copyFileSync(srcPath, join(TARGET, file));

    // Deduplicate slugs
    let slug = slugify(file);
    if (seenSlugs.has(slug)) {
      let i = 2;
      while (seenSlugs.has(`${slug}-${i}`)) i++;
      slug = `${slug}-${i}`;
    }
    seenSlugs.add(slug);

    const src = `/gifs/${file}`;
    const tags = deriveTags(srcPath, srcDir, folder);

    // Read dimensions via ImageMagick
    let width = 0;
    let height = 0;
    try {
      const out = execFileSync('magick', ['identify', '-format', '%w %h', `${join(TARGET, file)}[0]`], {
        encoding: 'utf-8',
        timeout: 5000,
      }).trim();
      const [w, h] = out.split(' ').map(Number);
      if (w && h) { width = w; height = h; }
    } catch {
      console.warn(`  Could not process: ${file}`);
    }

    entries.push({
      slug,
      alt: basename(file, extname(file)),
      src,
      width,
      height,
      tags,
      featured: featuredFiles.has(file),
    });
  }

  console.log(`${folder}: ${files.length} files`);
}

// Sort alphabetically by slug for stable output
entries.sort((a, b) => a.slug.localeCompare(b.slug));

// Generate YAML
const lines = [
  '# Auto-generated by scripts/sync-gifs.mjs — do not edit manually',
  '# except for `featured` flags. To re-sync, run: npm run sync-gifs',
  '',
];

for (const entry of entries) {
  lines.push(`- slug: ${entry.slug}`);
  lines.push(`  alt: "${entry.alt.replace(/"/g, '\\"')}"`);
  lines.push(`  src: "${entry.src}"`);
  if (entry.width && entry.height) {
    lines.push(`  width: ${entry.width}`);
    lines.push(`  height: ${entry.height}`);
  }
  if (entry.tags.length > 0) {
    lines.push(`  tags: [${entry.tags.map((t) => `"${t}"`).join(', ')}]`);
  }
  if (entry.featured) lines.push('  featured: true');
  lines.push('');
}

writeFileSync(YAML_PATH, lines.join('\n'));
console.log(`\nWrote ${entries.length} entries to ${YAML_PATH}`);
const featuredCount = entries.filter((e) => e.featured).length;
if (featuredCount > 0) console.log(`${featuredCount} marked as featured`);
const tagSet = new Set(entries.flatMap((e) => e.tags));
console.log(`${tagSet.size} unique tags: ${[...tagSet].sort().join(', ')}`);

// Upload to Google Cloud Storage
const GCS_BUCKET = 'gs://samm-bio-gifs';
console.log(`\nSyncing to ${GCS_BUCKET}...`);
try {
  execFileSync('gcloud', [
    'storage', 'rsync', TARGET, `${GCS_BUCKET}/gifs/`,
    '--recursive', '--delete-unmatched-destination-objects', '--exclude=featured/.*',
  ], { stdio: 'inherit', timeout: 300000 });
  console.log('GCS sync complete.');
} catch {
  console.warn('GCS sync failed — run manually: gcloud storage rsync public/gifs/ gs://samm-bio-gifs/gifs/ --recursive --exclude="featured/.*"');
}
