// Auto-generated by scripts/fetch-content.mjs — do not edit
import type { Show } from '@/lib/queries';

export const shows: Show[] = [
  {
    title: 'Goofs & Goblins: The Great Modron March',
    venue: 'Pocket Sandwich Theatre',
    venueUrl: 'https://www.pocketsandwich.com/',
    address: '1104 Elm Street, Carrollton, TX 75006',
    datetime: '2026-03-10T20:00',
    endDatetime: '2026-03-10T22:00',
    note: 'Doors at 7 PM. $12 / $10 students.',
  },
  {
    title: 'ACT Extreme Improv Challenge FINALS',
    venue: 'Cafe Bohemia',
    venueUrl: 'https://www.cafebohemia.net/',
    address: '2320 Los Rios Blvd, Suite 105, Plano, TX 75074',
    datetime: '2026-03-14T20:00',
    endDatetime: '2026-03-14T22:00',
    note: 'Pay what you can (suggested $10). Arrive by 7:30 for a good seat.',
  },
];
